name: TimeSeries
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - arviz=0.7.0=py_0
  - binutils_impl_linux-64=2.33.1=he1b5a44_7
  - binutils_linux-64=2.33.1=h9595d00_17
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - cftime=1.0.4.2=py36hc1659b7_0
  - convertdate=2.1.3=py_1000
  - curl=7.68.0=hf8cf82a_0
  - cycler=0.10.0=py_2
  - cython=0.29.15=py36h831f99a_1
  - ephem=3.7.7.1=py36h516909a_0
  - fbprophet=0.6=py36he1b5a44_0
  - freetype=2.10.0=he983fc9_1
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_17
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_17
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - holidays=0.10.1=py_0
  - icu=58.2=hf484d3e_1000
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py36hdb11119_1
  - krb5=1.16.4=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.68.0=hda55be3_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_5
  - liblapack=3.8.0=14_openblas
  - libnetcdf=4.7.3=nompi_h9f9fd6a_101
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - lunarcalendar=0.0.9=py_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - ncurses=6.2=he6710b0_0
  - netcdf4=1.5.3=nompi_py36hd35fb8e_102
  - numpy=1.18.1=py36h95a1406_0
  - openssl=1.1.1d=h7b6447c_4
  - packaging=20.1=py_0
  - pandas=1.0.2=py36h830a2c2_0
  - pip=20.0.2=py36_1
  - plotly=4.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pystan=2.19.1.1=py36hb3f55d8_1
  - python=3.6.10=h0371630_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.3=py_0
  - readline=7.0=h7b6447c_5
  - retrying=1.3.3=py36_2
  - scipy=1.4.1=py36h921218d_0
  - setuptools=46.0.0=py36_0
  - six=1.14.0=py_1
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py36h8c4c3a4_1
  - wheel=0.34.2=py36_0
  - xarray=0.15.0=py_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
prefix: /home/marcello/.conda/envs/TimeSeries

